DEPARTMENT = {
    'Paris', 
    'Haute-Garonne', 
    'Loire-Atlantique', 
    'Rhône', 
    'Gironde'

}

CITY =[
    'Paris',
    'Toulouse ',
    'Nantes ',
    'Lyon',
    'Bordeaux ',
    'Brignais ',
    'Saint-Sébastien-sur-Loire ',
    'Gradignan ',
    'Corbas ',
    'Blagnac ',
    'Labège ',
    'Treillières ',
    'Cestas ',
    'Balma ',
    'Limonest ',
    'Feyzin ',
    'Villeurbanne ',
    'Mérignac ',
    'Pessac ',
    'Chaponnay ',
    'Gironde',
    'La Tour-de-Salvagny ',
    'Saint-Herblain ',
    'Rhône',
    'Bron ',
    'Rillieux-la-Pape ',
    'Bègles ',
    'Carquefou ',
    'Portet-sur-Garonne ',
    'Châteaubriant ',
    'Saint-Priest ',
    'Eysines ',
    'Chassieu ',
    'Talence ',
    'Haute-Garonne',
    'Villeneuve-lès-Bouloc ',
    'Loire-Atlantique',
    'Thizy ',
    'Libourne ',
    'La Chapelle-sur-Erdre ',
    'Limas ',
    'Irigny ',
    'Bruges ',
    'Tassin-la-Demi-Lune ',
    'Vénissieux ',
    'Dardilly ',
    'Saint-Alban ',
    'Marennes ',
    'Écully ',
    'Grandchamps-des-Fontaines ',
    'Canéjan ',
    'Beauzelle ',
    'Caluire-et-Cuire ',
    'Martillac ',
    'Haute-Goulaine ',
    'Le Bouscat ',
    "Saint-Didier-au-Mont-d'Or ",
    'Saint-Père-en-Retz ',
    'Castanet-Tolosan ',
    'Lissieu ',
    'Mondonville ',
    'Genas ',
    'Montrabé ',
    'Oullins ',
    'Colomiers ',
    'Pierre-Bénite ',
    'Saint-Pierre-de-Chandieu ',
    'Saint-Genis-les-Ollières ',
    'Nation ',
    "Champagne-au-Mont-d'Or ",
    'Saint-Nazaire ',
    'Sainte-Luce-sur-Loire ',
    'Plessé ',
    'Ancenis ',
    'Solaize ',
    'Lormont ',
    'République ',
    'Villefranche-sur-Saône ',
    'Francheville ',
    'Montoir-de-Bretagne ',
    'Craponne ',
    'Rezé ',
    'Thouaré-sur-Loire ',
    "L'Union ",
    'Vourles ',
    'Saint-Orens-de-Gameville ',
    'Soulac-sur-Mer ',
    'Bassens ',
    'Bouguenais ',
    'Chasselay ',
    'Vertou ',
    'Le Haillan ',
    'Cornebarrieu ',
    'Montrottier ',
    'Colombier-Saugnieu ',
    'Toussieu ',
    'Charbonnières-les-Bains ',
    'Basse-Goulaine ',
    'La Chevrolière ',
    'Saint-Médard-en-Jalles ',
    "Marcy-l'Étoile ",
    'Meyzieu ',
    'Décines-Charpieu ',
    'Saint Martin du Touch ',
    'Vaulx-en-Velin '
 ]

CATEGORIES = [
    'Développeur', 
    'Data',
]

COMPANIES = [
    'talents rh', 
    'adsearch', 
    'cgi group, inc.', 
    'sept lieues', 
    'natixis',
    'criteo', 
    'airbus', 
    'externatic', 
    'expectra.fr', 
    'orange', 
    'manpower',
    'silkhom',
    'atos', 
    'joblift',
    'forum emploi-formation-alternance: talents handicap',
    'activus group', 
    'harnham', 
    'umanis', 
    'konekt', 
    'cts corporate',
    'easy partner', 
    'cgi', 
    'amaris', 
    'keyrus', 
    'gfi', 
    'synchrone', 
    'fortil',
    'hays', 
    'ingéniance', 
    'be free talent', 
    'econocom', 
    'unlck',
    'capgemini', 
    'michael page', 
    'euro information', 
    'akka technologies',
    'urban linker', 
    'thales group', 
    'labsoft', 
    'ingeniance',
    'cs communication & systèmes', 
    'ippon', 
    'bpce sa', 
    'adonis', 
    'conserto',
    'sword', 
    'e-quadra', 
    'ausy', 
    'tech valley', 
    'page personnel fr',

]

JOBS = [
    'ingenieur devops', 
    'data engineer', 
    'developpeur net',
    'data scientist', 
    'devops', 
    'data analyst', 
    'developpeur java',
    'developpeur web', 
    'developpeur full stack', 
    'developpeur php',
    'developpeur informatique', 
    'developpeur', 
    'consultant devops',
    'developpeur front end', 
    'software engineer', 
    'developpeur java j2ee',
    'developpeur python', 
    'devops engineer', 
    'developpeur java jee',
    'developpeur c++', 
    'architecte big data', 
    'ingenieur devops ',
    'developpeur big data', 
    'ingenieur systeme devops',
    'developpeur angular', 
    'data engineer ', 
    'developpeur net ',
    'integrateur devops', 
    'consultant data', 
    'ingenieur big data',
    'developpeur android', 
    'consultant big data', 
    'senior data scientist',
    'developpeur php symfony', 
    'data manager',
    'developpeur php symfony seniors',
    'senior software engineer',
    'developpeur mobile android ios', 
    'developpeur fullstack',
    'developpeur vb net', 
    'developpeur windev', 
    'analyste developpeur',
    'developpeur salesforce', 
    'architecte data', 
    'data scientist ',
    'chef projet data', 
    'consultant data scientist', 
    'data architect',
    'ingenieur cloud devops', 
    'developpeur python senior'
       ]

SKILLS = [
    'Python',
    'Java',
    'HTML_CSS',
    'Machine Learning',
    'Deep Learning',
    'Javascript',
    'Swift',
    'NoSql',
    'SQL',
    'Agile',
    'J2ee',
    'Jee',
    'Ruby',
    'Php',
    'Spark',
    'Big_data',
    'Scala',
    'Back_end',
    'Git',
    'R',
    'Powerbi',
    'Cloud',
    'C',
    'Docker',
    'ABAP',
    'WLang'
]

CONTRACTS = [
    'CDI',
    'CDD',
    'Freelance',
    'Stage',
]

QUALIFICATIONS = [
    'BTS',
    'Deug',
    'DUT',
    'IUT',
    'Licence',
    'Master',
    'Doctorat',
    'Ingénieur',
]